version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
