# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "node_modules/**/*"
    - "vendor/**/*"

# Overwrite or add rules to create your own house style
# Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: "no_space"
  Exclude:
    - "db/*schema.rb"

# Ignore block length in config files
Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "db/*.rb"
    - "spec/**/*.rb"

# Allow numbers in variable names in specs
Naming/VariableNumber:
  Exclude:
    - "spec/**/*.rb"

# Rspec
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitExpect:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  AllowSubject: true
  Max: 10
RSpec/NestedGroups:
  Max: 4
RSpec/ContextWording:
  Prefixes:
    - when
    - and
    - with
    - without
    - for

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/SymbolArray:
  EnforcedStyle: "brackets"
# Trailing commas make nicer diffs
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  EnforcedStyle: "brackets"
