default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      threads: <%= ENV.fetch("JOB_THREADS", 4) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
