production:
  schedule_checks:
    class: ScheduleChecksJob
    priority: 2
    queue: background
    schedule: every 10 minutes
  remove_orphan_tags:
    class: RemoveOrphanTagsJob
    queue: background
    schedule: every day at 2am
  remove_inactive_users:
    class: RemoveInactiveUsersJob
    queue: background
    schedule: "@monthly at 05:00"
  remove_inactive_teams:
    class: RemoveInactiveTeamsJob
    queue: background
    schedule: "@monthly at 06:00"
