production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    queue: background
    schedule: every day at 7:00 and 21:00
  remove_orphan_tags:
    class: RemoveOrphanTagsJob
    queue: background
    schedule: every day at 2am
  remove_inactive_users:
    class: RemoveInactiveUsersJob
    queue: background
    schedule: every month at 1am
  remove_inactive_sessions:
    class: RemoveInactiveSessionsJob
    queue: background
    schedule: every day at 1am
  remove_inactive_teams:
    class: RemoveInactiveTeamsJob
    queue: background
    schedule: every month at 2am
