production:
  remove_orphan_tags:
    class: RemoveOrphanTagsJob
    queue: background
    schedule: every day at 2am
  remove_inactive_users:
    class: RemoveInactiveUsersJob
    queue: background
    schedule: every month at 1am
  remove_obsolete_sessions:
    class: RemoveObsoleteSessionsJob
    queue: background
    schedule: every month at 1am
  remove_inactive_teams:
    class: RemoveInactiveTeamsJob
    queue: background
    schedule: every month at 2am
